site: Chatventure
url: https://jacudibu.com/Chatventure
title: Chatventure
description: The text-based Telegram MMORPG.
twitter:
  username: Jacudibu
  card: summary
  creator: Jacudibu
author:
  twitter: Jacudibu
  name: Jacudibu
  avatar:
  email: #youremail
  url: https://jacudibu.com
permalink: pretty

baseurl: "/"

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:year:month:day-:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"